UBC-MDS/What-Effects-One-Chance-of-Survival-on-the-Titanic-A-Logistic-Regression-Analysis

analysis_titanic_survival.ipynb
This PR contains the Title of our report along with the introduction and inspiration of the analysis we will be conducting. The reasoning behind the analysis, history, and application of the report in the future is explained here.
=> Beginning of Report - Title and Introduction

CODE_OF_CONDUCT.md, CONTRIBUTING.md
I have added the contributing.md and code_of_conduct.md
=> adding contributing and code of conduct

analysis_titanic_survival.ipynb
Add data set part in the notebook
=> add data section on notebook

environment.yaml
Hey guys,
I have created an environment yaml file and added the packages that I feel are necessary. Please feel free to download and create the environment on your local system and let me know if it works or if I need to make some edits.
=> Adding environment file

analysis_titanic_survival.ipynb
Hey guys, I have added the summary. Please review it and let me know if I missed out anything.
=> Added Summary

analysis_titanic_survival.ipynb
Add limitation. Our logistic regression model, used for exploratory analysis in the report, could be enhanced by testing its predictive accuracy on a test dataset and exploring other modeling techniques like Decision Trees and Random Forests for a more comprehensive and robust analysis.
=> add limitation

analysis_titanic_survival.ipynb
Add limitations and references to the notebook. Our logistic regression model, used for exploratory analysis in the report, could be enhanced by testing its predictive accuracy on a test dataset and exploring other modeling techniques like Decision Trees and Random Forests for a more comprehensive and robust analysis.
=> add limitation and reference

README.md
Updated the Readme file and added references
=> updated README and added reference

tests/testthat/test_data_wrangling_functions.R
functions testing select_columns() and clean_and_organize_data()
=> tests for data wrangling functions

R/data_wrangling_functions.R
R script containing select_columns() and clean_and_organize_data() functionm with doc strings
=> data wrangling functions for report R script

R/modeling_analysis_functions.R, tests/testthat/helper-modeling_analysis_functions.R, tests/testthat/test-modeling_analysis_functions.R
add summary_table function and some test cases for the function
=> add summary_table function and test cases

tests/testthat/test-EDA_functions.r
Hey guys, I have added tests for EDA functions. Please feel free to review and test it out.
=> Added tests for EDA functions

R/EDA_functions.R
Hey all, adding the EDA functions file here. Let me know if it looks fine to you all.
=> Adding EDA functions

tests/testthat/test-EDA_functions.r
Hey all, I have updated the test functions for the EDA. Please feel free to review and merge the branch.
=> Updated EDA test functions

analysis_titanic_survival.html
Uploading the .html of the report for that our git pages can access it for generating the report.
=> html report to root for Pages to access

scripts/EDA_scripts.R
Hey guys, 
I have added EDA script in this branch. I have tested the script file locally and it seems to work. 
Please feel free to review and complete the merge request!
=> Adding EDA script

README.md
Included the commands to run, to produce the elements of the report.
=> Update README.md - added script command calls

environment.yaml
=> Updated the yaml file to include the jupyter notebook and adde versions

environment.yaml
updated the yaml file to resolve the issue raised by Sampson
=> updated the yaml env file again

environment.yaml, report/_config.yml, report/_toc.yml, report/references.bib
Updated the environment file to get rid of grid and added the config, toc and references files.
=> Adding the updated yaml environment and config/toc/references file

docker-compose.yml
update docker image version in docker-compose file
=> update docker image version in docker-compose

makefile
Hey guys, added the makefile to this branch. As we have tested this in the lab, it should hopefully work without issue.
=> Adding the makefile

CHANGELOG.md
created CHANGELOG.md so everyone can modify it after completing their part of work
=> Create CHANGELOG.md template

report/analysis_titanic_survival.ipynb
This PR is to address the review question to why logistic regression is chosen, instead of other models including SVC, RF, etc.
=> added explanation to why logistic regression is chosen
